/**
 * Phase 37d — shared jsPDF helpers reused by all `/api/reports/*` endpoints.
 *
 * Pulled out of compliance-pdf so the new five document endpoints don't each
 * re-implement page-break math, footer signing, and the Movestock title block.
 *
 * Design Rule 6 enforcement lives here: `assertNoSensitiveValues` rejects any
 * field row whose label looks like an ID/passport/tax number AND whose value
 * is non-empty. PDF endpoints call it before drawing the form-summary section.
 */

import type { jsPDF } from 'jspdf'
import { formatSAST } from '@/lib/utils/date'

export const BRAND_BLUE: [number, number, number] = [37, 99, 235]
export const TEXT_GREEN: [number, number, number] = [22, 163, 74]
export const TEXT_AMBER: [number, number, number] = [217, 119, 6]
export const TEXT_RED: [number, number, number] = [220, 38, 38]

/** Add a new page if remaining space is less than `needed` mm. */
export function checkPageBreak(doc: jsPDF, y: number, needed: number): void {
  const pageHeight = doc.internal.pageSize.getHeight()
  if (y + needed > pageHeight - 20) {
    doc.addPage()
  }
}

/** Get the current Y position; reset to top of page if a break just happened. */
export function getCurrentY(doc: jsPDF, y: number): number {
  const pageHeight = doc.internal.pageSize.getHeight()
  if (y > pageHeight - 20) return 15
  return y
}

/** Draw the standard Movestock title block. Returns the next y position. */
export function drawHeader(
  doc: jsPDF,
  opts: { title: string; subtitle?: string | null; meta?: string[] },
): number {
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 15

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0)
  doc.text(opts.title, pageWidth / 2, y, { align: 'center' })
  y += 8

  if (opts.subtitle) {
    doc.setFontSize(13)
    doc.text(opts.subtitle, pageWidth / 2, y, { align: 'center' })
    y += 7
  }

  if (opts.meta && opts.meta.length > 0) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(opts.meta.join('   |   '), pageWidth / 2, y, { align: 'center' })
    y += 7
  }

  doc.setDrawColor(200)
  doc.line(14, y, pageWidth - 14, y)
  y += 8
  return y
}

/** Draw the "Generated by Movestock — date — page X of Y" footer on every page. */
export function drawFooter(doc: jsPDF, generatedAt: Date): void {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageCount = doc.getNumberOfPages()
  const stamp = formatSAST(generatedAt, 'dd MMM yyyy HH:mm')

  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(150)
    doc.text(
      `Generated by Movestock — ${stamp} SAST — Page ${p} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' },
    )
  }
  doc.setTextColor(0)
}

/**
 * Draw a list of label / value rows with a left-aligned label and a dotted
 * underline value (the form-summary look). Always leaves the value column
 * blank for any "ID / Passport" / "Tax number" row — Design Rule 6.
 */
export interface FormRow {
  label: string
  value: string | null
  /** When true, force-blank the value (used for ID/passport/tax fields). */
  blank?: boolean
  /** Trailing hint shown in grey: e.g. "(fill in yourself)". */
  hint?: string | null
}

export function drawFormRows(doc: jsPDF, startY: number, rows: FormRow[]): number {
  const pageWidth = doc.internal.pageSize.getWidth()
  const labelX = 14
  const valueX = 70
  const lineEnd = pageWidth - 14
  let y = startY

  for (const row of rows) {
    checkPageBreak(doc, y, 8)
    y = getCurrentY(doc, y)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0)
    doc.text(`${row.label}:`, labelX, y)

    doc.setFont('helvetica', 'normal')
    if (row.blank) {
      doc.setDrawColor(150)
      doc.setLineDashPattern([1, 1], 0)
      doc.line(valueX, y + 0.5, lineEnd, y + 0.5)
      doc.setLineDashPattern([], 0)
      if (row.hint) {
        doc.setFontSize(8)
        doc.setTextColor(120)
        doc.text(row.hint, valueX, y + 4)
      }
      y += 8
    } else {
      doc.setTextColor(0)
      const value = row.value ?? '—'
      const wrapped = doc.splitTextToSize(value, lineEnd - valueX)
      doc.text(wrapped, valueX, y)
      y += 5 * Math.max(1, wrapped.length)
    }

    doc.setTextColor(0)
  }

  return y + 2
}

/** Sensitive label patterns — rows whose `value` MUST stay blank. */
const SENSITIVE_LABEL = /(id\s*number|passport|tax\s*number|tax\s*ref)/i

/**
 * Throws if any FormRow has a sensitive label and a non-blank, non-null value.
 * Called by every endpoint before rendering — central enforcement of Design
 * Rule 6 so a future contributor can't accidentally leak PII via a PDF.
 */
export function assertNoSensitiveValues(rows: FormRow[]): void {
  for (const row of rows) {
    if (SENSITIVE_LABEL.test(row.label) && row.value && !row.blank) {
      throw new Error(
        `Design Rule 6 violation: row "${row.label}" carries a value. Sensitive personal numbers must never be embedded in generated PDFs.`,
      )
    }
  }
}

/** Build the `Content-Disposition` filename for a given report type. */
export function pdfFilename(prefix: string, generatedAt: Date): string {
  return `${prefix}-${formatSAST(generatedAt, 'yyyyMMdd')}.pdf`
}

/** Wrap a buffer into a download Response. */
export function pdfResponse(buffer: ArrayBuffer, filename: string): Response {
  return new Response(buffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}

/** Section heading helper. */
export function drawSectionHeading(doc: jsPDF, y: number, text: string): number {
  checkPageBreak(doc, y, 12)
  y = getCurrentY(doc, y)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0)
  doc.text(text, 14, y)
  return y + 6
}
